return {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    branch = "master",
    build = ':TSUpdate',
    config = function()
        require("nvim-treesitter.install").compilers = {'gcc'},
        require'nvim-treesitter.configs'.setup {
            ensure_installed = {
                'bash',
                'c',
                'c_sharp',
                'comment',
                'cpp',
                'css',
                'csv',
                'dart',
                'dockerfile',
                'go',
                'html',
                'http',
                'javascript',
                'json',
                'lua',
                'markdown',
                'markdown_inline',
                'nix',
                'norg',
                'python',
                'regex',
                'rust',
                'scss',
                'sql',
                'svelte',
                'tsx',
                'typst',
                'typescript',
                'vue',
                'xml',
                'yaml',
                'zig'
            },
            auto_install = true,
            highlight = { enable = true },
            indent = { enable = true },
        }
    end
}
